### ISSUE TITLE
cannot load such file -- better_errors

### ISSUE THREAD

**Issue by darkpixel** [rauhryan/huboard#484]
When deploying master to dokku (a clone of Heroku using their cedar stack), I get an error:

```
-----> Writing config/database.yml to read from DATABASE_URL
-----> Precompiling assets
       Running: rake assets:precompile
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/fog-core-1.25.0/lib/fog/core/collection.rb:144: warning: circular argument reference - filters
       rake aborted!
       cannot load such file -- better_errors
       /tmp/build/config/environments/development.rb:1:in `require'
       /tmp/build/config/environments/development.rb:1:in `<top (required)>'
       /tmp/build/rakefile:13:in `require'
       /tmp/build/rakefile:13:in `block in <top (required)>'
       Tasks: TOP => assets:precompile => app
       (See full trace by running task with --trace)
       !
       !     Precompiling assets failed.
       !
To dokku@--redacted--:huboard
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@--redacted--:huboard'
12:45:29 [aaron@zefram:~/code/huboard] master 1 ±
```

Any thoughts on what I might be doing wrong?

**Comment by rauhryan** [comment]
Bettererrors is in the development bundle

Try setting HUBOARD_ENV to oss 

Haven't tested it in a while tho

**Comment by darkpixel** [comment]
That did it.  I'll document it in the wiki.
